"""add organization_id fks

Revision ID: 729287aac28a
Revises: 6c34107f4b28
Create Date: 2026-01-20 15:18:19.835789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '729287aac28a'
down_revision = '6c34107f4b28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.add_column('organizations', sa.Column('org_type', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_column('organizations', 'created_at')
    op.add_column('risk_history', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.alter_column('risk_history', 'water_source_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('risk_history', 'risk_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key(None, 'risk_history', 'organizations', ['organization_id'], ['id'])
    op.add_column('water_sources', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'water_sources', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_sources', type_='foreignkey')
    op.drop_column('water_sources', 'organization_id')
    op.drop_constraint(None, 'risk_history', type_='foreignkey')
    op.alter_column('risk_history', 'risk_score',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=False)
    op.alter_column('risk_history', 'water_source_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('risk_history', 'organization_id')
    op.add_column('organizations', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_column('organizations', 'org_type')
    op.create_table('alerts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('water_source_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('acknowledged', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['water_source_id'], ['water_sources.id'], name=op.f('alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###