"""add risk history table

Revision ID: a4e10a2b730e
Revises: e1faf26138fc
Create Date: 2026-01-07 15:28:40.328998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e10a2b730e'
down_revision: Union[str, None] = 'e1faf26138fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_source_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['water_source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_history')
    # ### end Alembic commands ###
