"""create tables

Revision ID: d352735f6f75
Revises: a4e10a2b730e
Create Date: 2026-01-07 15:47:21.326880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd352735f6f75'
down_revision: Union[str, None] = 'a4e10a2b730e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_source_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['water_source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_history')
    # ### end Alembic commands ###
